all:
  io_omniture_plugin:
    tracker_class:          ioOmnitureTracker
    service_class:          ioOmnitureService
    javascripts:            [] # javscripts to load when firing off an omniture event.
    javascripts_dir:        '/js' # dir where javascripts are stored.

    # your unique account
    #account:                foo_bar

    # Whether or not to set the pageType to "errorPage" automatically on 404
    handle_404:             true
    params:
      enabled:              true
      insertion:            bottom
      account:              YOURACCOUNT
      page_name:            ~
      domain_name:          ~
      detect_flash_policy:  ~
      include_javascript:   true
