all:
  io_omniture_plugin:
    tracker_class:          ioOmnitureTracker
    service_class:          ioOmnitureService

    # Whether or not to set the pageType to "errorPage" automatically on 404
    handle_404:             true
    params:
      enabled:              false
      insertion:            bottom
      account:              YOURACCOUNT
      page_name:            ~
      domain_name:          ~
      detect_flash_policy:  ~
      include_javascript:   true
    

